FROM python:3.10-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir pandas numpy scikit-learn joblib matplotlib seaborn streamlit twilio
EXPOSE 8501
CMD ["streamlit", "run", "streamlit_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]